### ISSUE TITLE
Multiple Sub Folders not working

### ISSUE THREAD

**Issue by joptimus** [marknesh/storage-googledrive-export#17]
When I tried running this extension on my project, all it is doing is adding subfolders to my google drive and never the actual files.  

Main bucket
- Jan
- Feb
- March
- April

Each folder has more subfolders
- A
- B
- C
- D

Then within those subfolders there is a pdf. So the example path would be `[BUCKET]/Jan/A/file.pdf`

What I get in Google Drive is continous empty folders of Jan, Feb, March, April over and over again, up to 8 times each.  I never get the subfolder or the file to come over. When i try looking at the logs in Google Cloud, they do not seem very helpful and sometimes there is an error `Memory limit of 256 MiB exceeded with 257 MiB used. Consider increasing the memory limit, see https://cloud.google.com/functions/docs/configuring/memory` .  What am I doing wrong?

**Comment by marknesh** [comment]
Hi @joptimus, This seems to be occurring when uploading existing files, will implement a fix as soon as possible.

**Comment by joptimus** [comment]
@marknesh thank you, looking forward to it!  Its a great extension, I had been trying something similar for a while but never got to work right!

**Comment by marknesh** [comment]
@joptimus This issue is now fixed in v0.1.3. Please uninstall the extension and then reinstall to upload existing files using the same folder structure, since you can only upload existing files when installing the extension and not updating it. Also, increase the function memory and the function timeout when configuring the extension if you have large files, to prevent reaching the default memory limit of 256 MB.
